---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: volante-cars-lab

resources:
  - ../default/

patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'volante-cars-lab'
  - target:
      kind: Secret
      name: bmc-day2-worker1
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'bmc-du3-ldc1-volante-cars-lab'
  - target:
      kind: BareMetalHost
      name: bmh-day2-worker1
    path: ./patches/bmh-volante-cars-lab-du3-ldc1.yaml
  - target:
      kind: NMStateConfig
      name: nmstate-day2-worker1
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'nmstate-du3-ldc1-volante-cars-lab'
  - target:
      kind: NMStateConfig
    patch: |-
      - op: replace
        path: /metadata/labels/cluster-name
        value: 'volante-nmstate'
