---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: volante-cars-lab

resources:
  - github.com/redhat-partner-solutions/vse-ocp-bases/base/3-node?ref=main

patchesStrategicMerge:
  - ./patches/nmstate-config.yaml
  - ./patches/aci.yaml

patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'volante-cars-lab'
  - target:
      kind: AgentClusterInstall
    patch: |-
      - op: replace
        path: /spec/clusterDeploymentRef/name
        value: 'volante-cars-lab'
      - op: replace
        path: /metadata/name
        value: 'volante-cars-lab'
  - target:
      kind: SealedSecret
      name: assisted-deployment-pull-secret
    path: ./patches/pullsecret-sealed-patch.yaml
  - target:
      kind: Secret
      name: bmc-super1
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'volante-cars-lab-bmc-super1'
  - target:
      kind: Secret
      name: bmc-super2
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'volante-cars-lab-bmc-super2'
  - target:
      kind: Secret
      name: bmc-super3
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'volante-cars-lab-bmc-super3'
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'volante-cars-lab'
  - target:
      kind: BareMetalHost
      name: super1
    path: ./patches/bmh-volante-cars-lab-super1-patch.yaml
  - target:
      kind: BareMetalHost
      name: super2
    path: ./patches/bmh-volante-cars-lab-super2-patch.yaml
  - target:
      kind: BareMetalHost
      name: super3
    path: ./patches/bmh-volante-cars-lab-super3-patch.yaml
  - target:
      kind: ClusterDeployment
    path: ./patches/clusterdeployment-patch.yaml
  - target:
      kind: InfraEnv
    path: ./patches/infraenv-patch.yaml
  - target:
      kind: KlusterletAddonConfig
    path: ./patches/klusterletaddon-patch.yaml
  - target:
      kind: Provisioning
      name: provisioning-configuration
    patch: |-
      - op: replace
        path: /spec/disableVirtualMediaTLS
        value: true
