---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
 - skidoo-siteconfig.yaml

resources:
 - github.com/redhat-partner-solutions/vse-ocp-bases/base/ztp/site-config?ref=main

patches:
 - target:
    kind: Secret
   patch: |-
     - op: replace
       path: /metadata/name
       value: 'skidoo-bmc-creds-secret'
     - op: replace
       path: /metadata/namespace
       value: 'skidoo'
     - op: replace
       path: /data/username
       value: 'cm9vdA=='
     - op: replace
       path: /data/password
       value: 'YWx0aW9zdGFyMTIz'
 - target:
    kind: SealedSecret
   patch: |-
     - op: replace
       path: /metadata/name
       value: 'assisted-deployment-pull-secret'
     - op: replace
       path: /metadata/namespace
       value: 'skidoo'
     - op: replace
       path: /spec/encryptedData/.dockerconfigjson
       value: 'xxxxx'
     - op: replace
       path: /spec/encryptedData/type
     - op: replace
       path: /spec/template/metadata/name
       value: 'skidoo-bmc-creds-secret'
     - op: replace
       path: /spec/template/metadata/namespace
       value: 'skidoo'
