---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "skidoo"
  namespace: "skidoo"
spec:
  baseDomain: "cars.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.12.10-x86-64-appsub"
# yamllint disable-line rule:line-length
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
    - clusterName: "skidoo"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites: "r740xls"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        - cidr: fd01::/48
          hostPrefix: 64
      serviceNetwork:
        - 172.30.0.0/16
        - fd02::/112
      machineNetwork:
        - cidr: 10.60.0.0/24
        - cidr: fd00:6:6:2051::0/64
      additionalNTPSources:
        - registry.cars.lab
        - fd00:6:6:11::52
      nodes:
        - hostName: "super1.skidoo.cars.lab"
          role: master
# yamllint disable-line rule:line-length
          bmcAddress: "idrac-virtualmedia://172.28.11.29/redfish/v1/Systems/System.Embedded.1"
          bmcCredentialsName:
            name: "skidoo-bmc-creds-secret"
          bootMACAddress: "40:A6:B7:3D:B3:70"
          bootMode: "UEFI"
          cpuset: "0-3,48-51"
          nodeNetwork:
            interfaces:
              - name: "enp1s0"
                macAddress: "40:A6:B7:3D:B3:70"
            config:
              interfaces:
                - name: enp1s0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.60.0.60
                        prefix-length: 24
                  ipv6:
                    enabled: true
                    address:
                      - ip: fd00:6:6:2051::60
                        prefix-length: 64
                    autoconf: false
                    dhcp: false
              dns-resolver:
                config:
                  search:
                    - cars.lab
                  server:
                    - 10.40.0.100
                    - fd00:6:6:11::52
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 10.60.0.1
                    next-hop-interface: enp1s0
                  - destination: ::/0
                    next-hop-address: fd00:6:6:2051::1
                    next-hop-interface: enp1s0
