---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: github-cred
  - name: quay-cred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cicd-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: vse-cicd-catalog
