---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-partner-solutions/vse-ocp-bases/base/1-worker?ref=main

patchesStrategicMerge:
  - ./patches/nmstate-config.yaml

patches:
  - target:
      kind: BareMetalHost
      name: bmh-day2-worker1
    path: ./patches/bmh-cu1.yaml
