---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # yamllint disable-line rule:line-length
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-supermicro"
  namespace: "ztp-group"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    group-supermicro: ""
  mcp: "master"
  sourceFiles:
    - fileName: ConsoleOperatorDisable.yaml
      policyName: "config-policy"
    - fileName: StorageClass.yaml
      policyName: "config-policy"
      metadata:
        name: "lso-filesystemclass"
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        additionalKernelArgs:
          - crashkernel=512M
          #- cpufreq.default_governor=schedutil 30-Jan testing dcain
          - rcupdate.rcu_normal_after_boot=0
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "0-1, 32-33"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 16
        workloadHints:
          realTime: true
          #highPowerConsumption: true 30-Jan testing dcain
          perPodPowerManagement: false
        #net:
        #  userLevelNetworking: true #testing 30-Jan dcain
    - fileName: TunedPerformancePatch.yaml
      policyName: "config-policy"
      spec:
        profile:
          - name: performance-patch
            # yamllint disable-line rule:line-length
            # The cmdline_crash CPU set must match the 'isolated' set in the PerformanceProfile above
            data: |
              [main]
              summary=Config changes profile got from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [sysctl]
              kernel.timer_migration=1
              [scheduler]
              group.ice-ptp=0:f:10:*:ice-ptp.*
