---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  watchAllNamespaces: true
  provisioningNetwork: Disabled
  ### Since Provisioning is a global config, we add it under the hub cluster
  ### configuration.
  ### Some baremetal systems need HTTP access instead of HTTPS.
  ### For allowing it, we meed to set disableVirtualMediaTLS true.
  ### By default, disableVirtualMediaTLS is set to false (using HTTPS).
  ###
  ### Remove comments and track the changes in Argo CD
  # disableVirtualMediaTLS: true
