---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: catalog
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/redhat-partner-solutions/vse-catalog
        revision: main
        directories:
          - path: components/tekton/*
          - path: components/tekton/pipelineruns
            exclude: true
  template:
    metadata:
      name: 'cicd-{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/redhat-partner-solutions/vse-catalog
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
