---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: openshift-gitops
  finalizers:
    - null
spec:
  generators:
    - git:
        repoURL: https://github.com/redhat-partner-solutions/vse-carslab-hub
        revision: cars2
        directories:
          - path: core/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy: {}
      source:
        repoURL: https://github.com/redhat-partner-solutions/vse-carslab-hub
        targetRevision: cars2
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
