---
apiVersion: v1
kind: Namespace
metadata:
  name: policies-sub
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies
  namespace: openshift-gitops
spec:
  generators:
    - git:
# yamllint disable-line rule:line-length
        repoURL: https://github.com/redhat-partner-solutions/vse-carslab-hub.git
        revision: main
        directories:
          - path: clusters/ztp-policies/*
  template:
    metadata:
      name: '{{path.basename}}-policies'
    spec:
      project: ztp-app-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
      source:
        path: '{{path}}'
# yamllint disable-line rule:line-length
        repoURL: https://github.com/redhat-partner-solutions/vse-carslab-hub.git
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: policies-sub
