---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "bonneville"
  namespace: "bonneville"
spec:
  baseDomain: "cars.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.12.10-x86-64-appsub"
# yamllint disable-line rule:line-length
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
    - clusterName: "bonneville"
      clusterLabels:
        group-vdu: ""
        #common-49: true
        #sites: "smcx11"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        - cidr: fd01::/48
          hostPrefix: 64
      serviceNetwork:
        - 172.30.0.0/16
        - fd02::/112
      machineNetwork:
        - cidr: 172.18.0.0/24
        - cidr: fd00:6:6:2061::0/64
      additionalNTPSources:
        - registry.cars.lab
        - fd00:6:6:11::52
      nodes:
        - hostName: "du1-fec1.bonneville.cars.lab"
          role: master
# yamllint disable-line rule:line-length
          bmcAddress: "redfish-virtualmedia://172.28.11.39/redfish/v1/Systems/1/"
          bmcCredentialsName:
            name: "bonneville-bmc-creds-secret"
          bootMACAddress: "ac:1f:6b:e1:80:86"
          bootMode: "UEFI"
          cpuset: "0-1,24-25"
          nodeNetwork:
            interfaces:
              - name: eno1
                macAddress: "3c:ec:ef:1d:a0:ee"
              - name: eno2
                macAddress: "3c:ec:ef:1d:a0:ef"
              - name: ens1f0
                macAddress: "50:7c:6f:01:65:80"
              - name: ens1f1
                macAddress: "50:7c:6f:01:65:81"
              - name: ens2f0
                macAddress: "ac:1f:6b:e1:80:86"
              - name: ens2f1
                macAddress: "ac:1f:6b:e1:80:87"
            config:
              interfaces:
                - name: eno1
                  type: ethernet
                  state: down
                - name: eno2
                  type: ethernet
                  state: down
                - name: ens2f0
                  type: ethernet
                  state: up
                  ipv4:
                    address:
                      - ip: 172.18.0.51
                        prefix-length: 24
                    enabled: true
                  ipv6:
                    enabled: true
                    address:
                      - ip: fd00:6:6:2061::51
                        prefix-length: 64
                    autoconf: false
                    dhcp: false
                - name: ens1f0
                  type: ethernet
                  state: down
              dns-resolver:
                config:
                  search:
                    - cars.lab
                  server:
                    - 10.40.0.100
                    - fd00:6:6:11::52
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 172.18.0.1
                    next-hop-interface: ens2f0
                  - destination: ::/0
                    next-hop-address: fd00:6:6:2061::1
                    next-hop-interface: ens2f0
