---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "goldwing"
  namespace: "ztp-site"
spec:
  bindingRules:
    name: "goldwing"
  mcp: "master"
  remediationAction: enforce
  sourceFiles:
    - fileName: PtpConfigSlaveCvl.yaml
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
          - name: "slave"
            # This interface must match the hardware in this group
            interface: "eno3"
            ptp4lOpts: "-2 -s --summary_interval -4"
            phc2sysOpts: "-a -r -n 24"
