name: Kustomize Build Check
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  kustomize-lint:
    runs-on: ubuntu-latest
    env:
      KUSTOMIZE_VERSION: 3.9.4
    steps:
      - name: Install Kustomize
        # yamllint disable rule:line-length
        run: |
          sudo curl -L -o /usr/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64
          sudo chmod +x /usr/bin/kustomize
      - name: Checkout cnf-features-deploy repo
        uses: actions/checkout@v3
        with:
          repository: openshift-kni/cnf-features-deploy
          path: cnf-features-deploy
      - name: Install siteconfig plugin
        run: |
          cd /home/runner/work/vse-carslab-hub/vse-carslab-hub/cnf-features-deploy/ztp/siteconfig-generator-kustomize-plugin
          make build
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Validate Manifests
        run: ./home/runner/work/vse-carslab-hub/vse-carslab-hub/main/validate_manifests.sh
        # yamllint enable rule:line-length
